elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.6
  command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
    - ANONYMOUS_USER=true
